chrome_public_manifest_package = "moe.hx030.chromium"
trichrome_certdigest="10f908c76ee29de227c0073f6c6e4bcde728b5d485047df71b7147df54020012"
is_desktop_android = true
target_os = "android"
target_cpu = "arm64"
is_component_build = false
is_debug = false
is_official_build = true
symbol_level = 1
disable_fieldtrial_testing_config = true
ffmpeg_branding = "Chrome"
proprietary_codecs = true
enable_vr = false
enable_arcore = false
enable_openxr = false
enable_cardboard = false
enable_remoting = false
enable_reporting = false
google_api_key = "x"
google_default_client_id = "x"
google_default_client_secret = "x"

use_siso = false
use_login_database_as_backend = true
build_contextual_search = false
dcheck_always_on = false
enable_iterator_debugging = false
exclude_unwind_tables = false
icu_use_data_file = true
rtc_build_examples = false
use_errorprone_java_compiler = false
use_rtti = false
enable_av1_decoder = true
enable_dav1d_decoder = true
include_both_v8_snapshots = false
include_both_v8_snapshots_android_secondary_abi = false
v8_enable_drumbrake = false
v8_drumbrake_bounds_checks = false
generate_linker_map = true


android_static_analysis = "off"

enable_stripping=true
strip_debug_info=true
enable_resource_allowlist_generation=false
optimize_for_size=true

v8_symbol_level=0
use_thin_lto=true
thin_lto_enable_optimizations=true
enable_pdf=false
enable_rlz=false


android_channel="stable"
blink_symbol_level=0
chrome_pgo_phase=2
debuggable_apks=false
disable_android_lint=true
enable_hangout_services_extension=false
enable_mdns=false
enable_mse_mpeg2ts_stream_parser=true
enable_platform_dolby_vision=true
enable_platform_hevc=true
is_cfi=false
treat_warnings_as_errors=false
use_debug_fission=false
use_official_google_api_keys=false
use_stable_package_name_for_trichrome=false